### ISSUE TITLE
Install of IfcConnetor on a Raspberry Pi 3 or 4

### ISSUE THREAD

**Issue by mangrove-art** [erneagholzbau/ifcconnector#3]
#### Here is a tutorial for a complete install of IfcConnetor on a Raspberry Pi 3 or 4

Testet on a Raspberry Pi 4 - 4GB

First download from [https://downloads.raspberrypi.org/raspios_lite_arm64/images/](url) the lastest image of Raspian lite 64.

Burn the image with [Raspberry Pi Imager](https://www.raspberrypi.com/software/) V 1.6.2 or higher to a SD Card. With `ctrl + shift + x` define options for your Raspberry Pi setup:
Set: Hostname: nameofyourpi.local
Set: SSH: true
Set: Password: Password for you Pi

After inserting the SD-Card to your Pi connect it to your network, power on and search for it in your local network with f.ex. [Advanced IP Scanner](https://www.advanced-ip-scanner.com/)

Once you found the IP Adress of your Pi create a terminal session into your Pi with f.ex. [Putty](https://www.putty.org/). Use as user `pi` and the `password` you've defined before (note that terminal doesn't show characters while you type your password).

#### Update, upgrade and reboot your Pi to start

`pi@nameofyourpi $ sudo apt update`
`pi@nameofyourpi $ sudo apt upgrade`
`pi@nameofyourpi $ sudo reboot -n`

#### Make shure your Pi is running on the right 64bit system
`pi@nameofyourpi $ uname -a`
should quote you an aarch64 system like so:
`Linux nameofyourp 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux`
#### Docker
see if docker is installed by default with
`pi@nameofyourpi $ docker`
if not
`pi@nameofyourpi $ curl -sSL https://get.docker.com -o install-docker.sh`
`pi@nameofyourpi $ bash install-docker.sh`
`pi@nameofyourpi $ sudo usermod -aG docker $USER`
`pi@nameofyourpi $ newgrp docker`
and test it
`pi@nameofyourpi $ docker run hello-world`
should create an output "Hello World" in terminal. Stop the container with `ctrl+c`.
NOTE:
To show all running containers:
`pi@nameofyourpi $ docker ps -a`
To erase a container:
`pi@nameofyourpi $ docker rm nameofcontainer`
#### Install Git
`pi@nameofyourpi $ sudo apt-get install git`
Once the command output has completed, you can verify the installation by typing: 
`pi@nameofyourpi  $ git version`
#### Installation of ifcconnector
Clone the Git repository in the directory ´home/pi/`
`pi@nameofyourpi:~ $ cd /home/pi'
`pi@nameofyourpi /home/pi $ ls -a`will list all files and directories
`pi@nameofyourpi /home/pi $ git clone https://github.com/erneagholzbau/ifcconnector`
#### install docker compose
Verify if cocker compose is already installed
`pi@nameofyourpi /home/pi $ docker-compose`
if not:
`pi@nameofyourpi /home/pi $ sudo apt install docker-compose`
#### Create local directories 
`pi@nameofyourpi /home/pi $ mkdir IfcConnectorDb`
`pi@nameofyourpi /home/pi $ mkdir IfcConnectorSnapshots`
#### Copy docker compose example and create a local configuration
`pi@nameofyourpi /home/pi $ cd ifcconnector/`
`pi@nameofyourpi /home/pi/ifcconnector $ cp docker-compose.traefik_example.yml docker_compose.yml`
#### Modify docker_compose.yml with your local parameters
`pi@nameofyourpi /home/pi/ifcconnector $ nano docker_compose.yml`
4 changes have to be made:

```
version: '3'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --api.insecure=true
      - --accesslog
      - --log
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:latest ****1. CHANGE HERE: -> put here 4.4 instead of latest -> image: mongo:4.4**
    container_name: mongodb
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /local/path/on/host/to/store/the/database:/data/db ****2. CHANGE HERE: -> put here: /home/pi/IfcConnectorDb:/data/db
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - backend

  ifcconnector:
    container_name: ifcconnector
    build: ./
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - /local/path/on/host/to/store/the/database_snapshots:/data/snapshots ****3. CHANGE HERE: -> put here: /home/pi/IfcConnectorSnapshots:/data/snapshots**
    labels:
      - traefik.enable=true
      - traefik.http.services.ifcconnector.loadbalancer.server.port=80
      - traefik.http.routers.ifcconnector.service=ifcconnector
      - traefik.http.routers.ifcconnector.rule=Host(`yourserver.domain_or_ip.org`) ****4. CHANGE HERE: -> put here instead of yourserver.domain_or_ip.org the ip adress of your PI you've found previously with Advanced Ip Scanner f.ex 192.168.1.134-> traefik.http.routers.ifcconnector.rule=Host(`192.168.1.134`)**

    networks:
      - backend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true
```
Save with `ctrl+o`and exit with `ctrl+x`

#### Make executable the start script
Execute in home/user/ifcconnector
`pi@nameofyourpi /home/pi/ifcconnector $ chmod +x app/start.sh`
#### Write .env file
Execute in home/user/ifcconnector
`pi@nameofyourpi /home/pi/ifcconnector $ nano .env`
Paste:
```
MONGO_DETAILS=mongodb://mongodb:27017
SNAPSHOTS_VOLUME_DIR=/data/snapshots
```
in there and save with `ctrl+o`and exit with `ctrl+x`
### Start container
  `pi@nameofyourpi /home/pi/ifcconnector sudo docker-compose -f docker_compose.yml up --build`
The containers should start, this may take a little while. When the terminal says 'ifcconnector started' go to your webbrowser and type in the address bar: the ip adress of your PI you've found previously with Advanced Ip Scanner f.ex 192.168.1.134/dashboard
If you get a dashboard showing different services running you're instance of ifcConnector is running.
The ifcConnector can be reached at: youripadress/docs or youripadress/redocs. For use refer to the main section.

Running the IfcConnector in a `tmux` session will allow you to close your terminal without stopping the running docker container. 
Install tmux:
`pi@nameofyourpi /home/pi/ $ sudo apt install tmux`
and start a new session with name ifcconnector:
`pi@nameofyourpi /home/pi/ $ sudo tmux new -s ifcconnector`
Then start the ifcConnector in the new session as previously described. For further information about `tmux` look here: [tmuxcheatsheet](https://tmuxcheatsheet.com/)
